# Generated by Django 4.2.7 on 2026-05-19 23:32

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_customer_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Máximo 5 MB. Formatos: JPG, PNG, GIF.', null=True, upload_to=store.models.product_image_path, validators=[store.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(help_text='Peso en gramos'),
        ),
    ]
